import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import { AlertSeverity } from './alert.entity';
import { LogLevel } from '../../logs/entities/log.entity';

export enum RuleConditionType {
  ERROR_COUNT = 'error_count',
  ERROR_RATE = 'error_rate',
  LOG_LEVEL = 'log_level',
  KEYWORD_MATCH = 'keyword_match',
  AI_ANOMALY = 'ai_anomaly',
  NO_LOGS = 'no_logs',
  CUSTOM = 'custom',
}

export enum RuleStatus {
  ENABLED = 'enabled',
  DISABLED = 'disabled',
  TESTING = 'testing',
}

export interface RuleCondition {
  type: RuleConditionType;
  // For error_count: { threshold: 10, timeWindowMinutes: 5 }
  // For error_rate: { threshold: 0.5, timeWindowMinutes: 5 }
  // For log_level: { levels: ['error', 'fatal'] }
  // For keyword_match: { keywords: ['timeout', 'connection refused'], matchAll: false }
  // For ai_anomaly: { minConfidence: 0.8, anomalyTypes: ['security_concern'] }
  // For no_logs: { timeWindowMinutes: 10 }
  params: Record<string, any>;
}

export interface RuleAction {
  type: 'email' | 'webhook' | 'slack' | 'in_app';
  config: Record<string, any>;
}

@Entity('alert_rules')
@Index(['status', 'sourceId'])
export class AlertRule {
  @ApiProperty()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({ example: 'High Error Rate Alert' })
  @Column()
  name: string;

  @ApiProperty({ example: 'Triggers when error rate exceeds 50%' })
  @Column('text', { nullable: true })
  description?: string;

  @ApiProperty({ description: 'Owner of this rule' })
  @Column()
  ownerId: string;

  @ApiProperty({ description: 'Applies to specific source (null = all)' })
  @Column({ nullable: true })
  @Index()
  sourceId?: string;

  @ApiProperty({ enum: RuleStatus })
  @Column({
    type: 'simple-enum',
    enum: RuleStatus,
    default: RuleStatus.ENABLED,
  })
  @Index()
  status: RuleStatus;

  @ApiProperty({ description: 'Severity of alerts generated by this rule' })
  @Column({
    type: 'simple-enum',
    enum: AlertSeverity,
    default: AlertSeverity.MEDIUM,
  })
  severity: AlertSeverity;

  @ApiProperty({ description: 'Rule conditions (all must match)' })
  @Column({ type: 'simple-json' })
  conditions: RuleCondition[];

  @ApiProperty({ description: 'Actions to take when rule triggers' })
  @Column({ type: 'simple-json' })
  actions: RuleAction[];

  @ApiProperty({ description: 'Minimum time between alerts (minutes)' })
  @Column({ type: 'integer', default: 5 })
  cooldownMinutes: number;

  @ApiProperty({ description: 'Last time this rule triggered' })
  @Column({ nullable: true })
  lastTriggeredAt?: Date;

  @ApiProperty({ description: 'Total times this rule has triggered' })
  @Column({ type: 'integer', default: 0 })
  triggerCount: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
